databases:
  - name: budget_app_development
    databaseName: budget_app_development
    user: budget_app_development

services:
  - type: web
    name: budget_app_development
    env: ruby
    buildCommand: "bundle exec rails assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
